### ISSUE TITLE
I can't still teleport players away while in combat.

### ISSUE THREAD

**Issue by christiaanbruijnes** [MinelinkNetwork/CombatTagPlus#67]
I can't still teleport players away while in combat.

**Comment by chrisbruijnes** [comment]
Bump.

**Comment by chrisbruijnes** [comment]
@Byteflux

**Comment by chrisbruijnes** [comment]
Bump....

**Comment by Byteflux** [comment]
Bump this all you want. It's an open source project and you're free to fix it yourself or get someone else to fix it. As much as I wish I could, I am too busy running two Minecraft networks to fix issues that don't affect me.

**Comment by Techcable** [comment]
How are you attempting to teleport players away?

**Comment by Techcable** [comment]
Does this happen in the latest build with 'untag-on-plugin-teleport' set to false?

**Comment by Techcable** [comment]
I highly suspect this has been fixed by 60849e5fc15c43f71f7c0015d8891610e3bc9a5b.
I'll reopen this if/when you provide sufficient-information.

**Comment by christiaanbruijnes** [comment]
I am using the latest version with a clean config.

**Bug 1:**
https://github.com/MinelinkNetwork/CombatTagPlus/commit/84a8463ed64f1557d26a7bd524818eea7c3c0d91 < These messages are both gray.

**Bug 2:**
The commands which are disabled are having two slashes.

**Bug 3:**
I tried to teleport players away in combat with Skript and Essentials (/spawn <player>, /tp <player> etc..)

**Comment by christiaanbruijnes** [comment]
Can you re-open this issue please? They aren't fixed yet! Bug 2 and 3 still exists.

**Comment by Techcable** [comment]
Could you please open seperate issues for 2 and 3?
